/*
 * Copyright (c) 2015 The NW1 Group
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 */

/*
 * Defines offsets into the configuration space for various modules
 */

ConfigurationManager_acbOffset          = 0x020
ConfigurationManager_transport1Offset   = 0x040
ConfigurationManager_transport2Offset   = 0x080
ConfigurationManager_transport3Offset   = 0x0C0
ConfigurationManager_nodeVarsOffset     = 0x100
ConfigurationManager_applicationOffset  = 0x200
ConfigurationManager_eventssOffset      = 0x3E0

