/*
 * Copyright (c) 2015 The NW1 Group
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 */

/*
 * Configuration constants
 *
 */

/*
 * Record Type
 *
 */

#define CONFIG_REC_UNUSED   0xff
#define CONFIG_REC_SETTINGS 1
#define CONFIG_REC_DATA     2

/*
 * Data Type
 *
 */

#define CONFIG_DATA_UNUSED  0xff
#define CONFIG_DATA_SERVO   1
#define CONFIG_DATA_RED     2
#define CONFIG_DATA_YELLOW  3
#define CONFIG_DATA_GREEN   4
#define CONFIG_DATA_WHITE   5

/*
 * Data offsets
 *
 */

#define CONFIG_REC_OFFSET   0
#define CONFIG_TYPE_OFFSET  1
#define CONFIG_DATA_OFFSET  2


