/*
 * Copyright (c) 2015 The NW1 Group
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 */

#define DisplayDrv_init                     DisplayDriverI2C_init
#define DisplayDrv_sendCommands             DisplayDriverI2C_sendCommands
#define DisplayDrv_sendCommand              DisplayDriverI2C_sendCommand
#define DisplayDrv_sendCommandAndParameter  DisplayDriverI2C_sendCommandAndParameter
#define DisplayDrv_sendData                 DisplayDriverI2C_sendData
