/*
 * Copyright (c) 2015 The NW1 Group
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 */

FontHeader_Size                 = 8
FontHeader_IdOffset             = 0
FontHeader_InfoOffset           = 1
FontHeader_MinCharOffset        = 2
FontHeader_MaxCharOffset        = 4
FontHeader_CharHeightOffset     = 6

FontGlyphEntry_Size             = 4
FontGlyphEntry_CharWidthOffset  = 0
FontGlyphEntry_CharDataOffset   = 0
